wandb_version: 1

do_optimization:
  value: false
fusion_method:
  value: visibility_weighted
opt_iters:
  value: 30
uv_size:
  value: 512
visibility_threshold:
  value: 0.3873210544796485
w_tv:
  value: 0.00976891268451506
