wandb_version: 1

do_optimization:
  value: false
fusion_method:
  value: average
opt_iters:
  value: 30
uv_size:
  value: 512
visibility_threshold:
  value: 0.45767983230853626
w_tv:
  value: 0.00041683990374134056
