wandb_version: 1

do_optimization:
  value: false
fusion_method:
  value: average
opt_iters:
  value: 30
uv_size:
  value: 512
visibility_threshold:
  value: 0.1952127252787293
w_tv:
  value: 1.473061227657936e-05
