wandb_version: 1

do_optimization:
  value: true
fusion_method:
  value: max_visibility
opt_iters:
  value: 100
uv_size:
  value: 512
visibility_threshold:
  value: 0.33528386808711463
w_tv:
  value: 2.7001255375645748e-05
