wandb_version: 1

do_optimization:
  value: false
fusion_method:
  value: visibility_weighted
opt_iters:
  value: 50
uv_size:
  value: 512
visibility_threshold:
  value: 0.5566525960810434
w_tv:
  value: 0.00013619857268749562
