wandb_version: 1

do_optimization:
  value: false
fusion_method:
  value: visibility_weighted
opt_iters:
  value: 100
uv_size:
  value: 512
visibility_threshold:
  value: 0.29049600222614125
w_tv:
  value: 1.0021568224458176e-05
