wandb_version: 1

do_optimization:
  value: false
fusion_method:
  value: visibility_weighted
opt_iters:
  value: 100
uv_size:
  value: 512
visibility_threshold:
  value: 0.23826084328203437
w_tv:
  value: 0.009467601898911613
